---
title: "Prototype Study Prepare Garmin Data"
author: "Craig W. Slinkman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages and required functions

```{r}
require( here )                        # Used to determine project location.
require( tidyverse )                   # I live in the tidyverse.
require( lubridate )                   # For date-time processing.
require( flextable )

source("D:/R-Projects/MyExercise/functions/find_all_garmin_csv_files.R")
source("D:/R-Projects/MyExercise/functions/read_garmin_csv_file.R")
source("D:/R-Projects/MyExercise/functions/find_last_pooled_date_time.R")
source("D:/R-Projects/MyExercise/functions/display_tibble.R")
```

## Find project data directory

```{r}
project_directory <-                  # Determine project location in 
  here()                              # operating system file system.

data_directory <-                     # Build file path to data directory.
  file.path( project_directory,
             "data")     
```

## Build an array of all activirty files in data directory

```{r}
files <-                              # Build an array to hold full project
  find_all_garmin_csv_files(          # file paths.
     data_directory )

files <-                             # Ensure files in ascending order by 
  sort( files )                      # by date.
```
  
## Read first Garmin Activity file by date.

```{r}
Pooled_Activities <-                  # Read first Garmin csv files and save 
  read_garmin_csv_file( files[1])     # History. 

display_tibble( Pooled_Activities )   # Display tibble.
```

## Read second activities file

```{r}
Activities <-                         # Read first Garmin csv files and save 
  read_garmin_csv_file( files[2]) %>% # History and ensuer that rows are in
    arrange( date_time )              # chronological order

display_tibble( Activities )          # Display tibble.  
```

## Merge Activities tiblles with History

```{r}
last_pooled_date_time <-                    # Find the last activity date in the pooled
  find_last_pooled_date_time(              # activities.
    Pooled_Activities )


Activities <-                               # Remove duplicates in Activities
  Activities %>%                            # tibble.
    filter( date_time > 
              last_pooled_date_time )

Pooled_Activities <-                        # Concatenate the remaining 
  Pooled_Activities %>%                     # Activities to the end of the
  bind_rows( Activities )                   # Pooled_Activities.

display_tibble( Pooled_Activities )         # Verify tibble.

```


## Logic to construct the Pooled_Activities tibble

```{r}
Pool_Activities <-                    # Read first Garmin csv file into tibble.
  read_garmin_csv_file( files[1])    

for( j in 2:length(files)){           # Loop through the remaing csv files.
  
  last_pooled_date_time <-           # Determine date of last chronological
    find_last_pooled_date_time(      # entry.
     Pooled )
  
  Activities <-                       # Read csv file.
     read_garmin_csv_file( files[j])
  
  Activities <-                       # Keep only rows with date_time ilder than
    Activities %>%                    # oldest date_time in the 
      filter( date_time >             # Pooled_Activities.
              last_pooled_date_time )
  
 Pooled_Activities <-                 # Concatenate Activities to the end of
   Pooled_Activities %>%              # Pooled_Activities.
      bind_rows( Activities )
}

dim( Pooled_Activities )

display_tibble(                             # Display tibble.
  Pooled_Activities)
```

